<?php defined("BASEPATH") OR exit("No direct script access allowed");$active_group = "default";
          $query_builder = TRUE;
$db["default"] = array("dsn"  => "",
"hostname" => "localhost", 
"username" => "exprete0_adis" ,
"password" => "{.]cbz5l.yQeT[",
"database" => "exprete0_driverapp",
"dbdriver" => "mysqli",
"pconnect" => FALSE,
"db_debug" => (ENVIRONMENT !== "production"),
"cache_on" => FALSE,
"cachedir" => "",
"char_set" => "utf8",
"dbcollat" => "utf8_general_ci",
"swap_pre" => "",
"encrypt" => FALSE,
"compress" => FALSE,
"stricton" => FALSE,
"failover" => array(),
"save_queries" => TRUE);
